version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gestionpyme-postgres
    restart: always
    environment:
      POSTGRES_USER: gp
      POSTGRES_PASSWORD: gp
      POSTGRES_DB: gp
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    container_name: gestionpyme-redis
    command: redis-server --requirepass gp
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
